src/Entity/Post.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\PostRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: PostRepository::class)]
#[Vich\Uploadable] 
#[ORM\HasLifecycleCallbacks]
class Post
{
  use Timestampable;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(min :3)]
    private $title;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $mini_title;

    #[ORM\Column(type: 'string', length: 255)]
    private $One_word_pov;

    #[ORM\Column(type: 'integer')]
    private $mark;

    #[ORM\Column(type: 'string', length: 255)]
    private $slug;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $location;

    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\NotBlank]
    private $review_article;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     */
    #[Vich\UploadableField(mapping: 'post_image', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageName;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMiniTitle(): ?string
    {
        return $this->mini_title;
    }

    public function setMiniTitle(?string $mini_title): self
    {
        $this->mini_title = $mini_title;

        return $this;
    }

    public function getOneWordPov(): ?string
    {
        return $this->One_word_pov;
    }

    public function setOneWordPov(string $One_word_pov): self
    {
        $this->One_word_pov = $One_word_pov;

        return $this;
    }

    public function getMark(): ?int
    {
        return $this->mark;
    }

    public function setMark(int $mark): self
    {
        $this->mark = $mark;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getReviewArticle(): ?string
    {
        return $this->review_article;
    }

    public function setReviewArticle(?string $review_article): self
    {
        $this->review_article = $review_article;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

     /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable());
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

   
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('imageFile', VichImageType::class, [
            'label' => 'Insert Image place here',
            'required' => false,
            'allow_delete' => true,
            'delete_label' => 'delete',
            'download_uri' => false,
            'image_uri' => true,
            'imagine_pattern' => 'squard_sm'
        ])
            ->add('title')
            ->add('mini_title')
            ->add('One_word_pov',ChoiceType::class,[
                'choices'  => [
                  'Good' => 'Good',
                  'Average' => 'Average',
                  'Bad' => 'Bad',
                ],])
            ->add('mark',ChoiceType::class,[
                'choices' => [
                  '10'=> '10',
                  '5' =>'5',
                  '1'=> '1',
                ]
              ,])
            ->add('location')
            ->add('review_article',TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use App\Service\PostService;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostsController extends AbstractController
{
    #[Route('/', name: 'app_posts',methods: 'GET')]
    public function index(PostRepository $postRepository): Response
    {
      
        $post = $postRepository->findBy([],['createdAt'=>'DESC']);
        return $this->render('posts/index.html.twig', ['posts' => $post]);
    }

    #[Route('/posts/create', name: 'app_posts_create', methods: 'GET|POST')]
    #[Security("is_granted('ROLE_USER') ")]
    public function create(Request $request, PostService $postService): Response
    {
      $this->denyAccessUnlessGranted('ROLE_USER');
      $post = new Post;
      $form= $this->createForm(PostType::class,$post);

       $form->handleRequest($request);

       if($form->isSubmitted() && $form->isValid()){
          $post->setUser($this->getUser());
          $postService->createPost($post);

          $this->addFlash('success','Post succefully created !');

          return $this->redirectToRoute('app_posts');

       }

      return $this->render('posts/create.html.twig',[
        'formPosts'=>$form->createView()]);
    }

    #[Route('/posts/{slug}', name: 'app_posts_details', methods:'GET')]
    public function show(Post  $post): Response
    {
      $this->denyAccessUnlessGranted('ROLE_USER');
      return $this->render('posts/show.html.twig', compact('post'));
    }

    #[Route('/posts/{slug}/edit', name: 'app_posts_edit', methods:'GET|POST')]
    #[Security("is_granted('ROLE_USER') && post.getUser()==user")]
    public function edit(Post $post,EntityManagerInterface $em,Request $request): Response
    {
      
      
      $form= $this->createForm(PostType::class, $post);

      $form->handleRequest($request);

      if($form->isSubmitted() && $form->isValid()){
         $em->flush();
         $this->addFlash('success','Post succefully updated !');
         return $this->redirectToRoute('app_posts');

      }

      return $this->render('posts/edit.html.twig', [
        'post' =>$post,
        'formEditPost' => $form->createView()
      ]);
    }

    #[Route('/posts/{slug}', name: 'app_posts_delete', methods:'DELETE')]
    #[Security("is_granted('ROLE_USER') && post.getUser()==user")]
    public function delete(Post $post,EntityManagerInterface $em,Request $request): Response
    {
      if($this->isCsrfTokenValid('post_deletion'.$post->getSlug(), $request->request->get('csrf_token'))){
        $em->remove($post);
        $em->flush();
        $this->addFlash('info','Post succefully deleted !');
      }
    
    return $this->redirectToRoute('app_posts');
    }
}

templates/posts/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'New Post' %}


{% block body %}
 
     <div class="row">
         <div class="col-md-6 mx-auto">
      
      <h1> Create Post</h1>
   
      {{ form_start(formPosts)}}
      
      {{ form_widget(formPosts)}}

      <input type="submit" value="Create Post" class="btn btn-primary">
      {{ form_end(formPosts)}}

         </div>
     </div>
 
   

{% endblock %}
 

templates/posts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title 'Edit Post #' ~ post.id %}


{% block body %}

<div class="row">
         <div class="col-md-6 mx-auto">
      
      <h1> Edit Post #{{ post.id }}</h1>
   
   {{ form_start(formEditPost)}}
      
      {{ form_widget(formEditPost)}}

      <input type="submit" value="Edit Post" class="btn btn-primary">
   {{ form_end(formEditPost)}}

         </div>
     </div>

  

{% endblock %}
 

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'dwira blanca' %}


{% block body %}
{% if posts|length >0 %}
   <h1 class="text-center text-muted mb-4"> {{ pluriel(posts|length,'Post','Posts') }} </h1>

   {% for row in posts|batch(3) %}
   <div class="row mb-5">
   {% for post in row %}
   <div class="col-md-4">
   <article class="bg-white rounded shadow post">
   <div class="mw-100 rounded-top overflow-hidden">
   {% if post.imageName %}
      <a href="{{  path('app_posts_details',{slug: post.slug }) }}"><img src="{{  vich_uploader_asset(post) | imagine_filter('squard_med') }}" alt="{{ post.title }}" class="w-100 "></a>  
      {% else %}
       <a href="{{  path('app_posts_details',{slug: post.slug }) }}"><img src="{{  asset('images/placeholder.jpg') | imagine_filter('squard_med') }}" alt="{{ post.title }}" class="w-100 "></a>
      {% endif %}
      </div>
      <h2 class="h5 ps-5 pt-3"><a href="{{  path('app_posts_details',{slug: post.slug }) }}" class="text-secondary text-muted text-decoration-none ">{{ post.title }}</a></h2>
      <p class="ps-5 pb-3 text-muted"><small>Submitted at {{ post.createdAt|ago }} by {{ post.user.userName }} </small></p>
       </article>
       </div>
      {% endfor %}
      </div>
      {% endfor %}
      
  
   {% else %}
    <p class="h1 text-center">No post Yet ! <a href="{{ path('app_posts_create')}}">Soyez le 1er a créer un post !</a></p>
   {% endif %}
{% endblock %}
 

templates/posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title post.title %}


{% block body %}
<div class="row">
<div class="col-md-6 mx-auto">
<article>
 
<article class="bg-white rounded shadow post">
   <div class="mw-100 rounded-top overflow-hidden">
   {% if post.imageName %}
      <img src="{{  vich_uploader_asset(post) | imagine_filter('squard_med') }}" alt="{{ post.title }}" class="w-100 ">  
      {% else %}
      <img src="{{  asset('images/placeholder.jpg') | imagine_filter('squard_med') }}" alt="{{ post.title }}" class="w-100 ">
      {% endif %}
      </div>
      <h2 class="h5 ps-5 pt-3 text-secondary text-muted">{{ post.title }}</h2> 
      <p class="ps-5 pb-3 text-muted"><small>Submitted at {{ post.createdAt|ago }} by {{ post.user.userName }}</small></p>
      <h3 class="h6 ps-5 pt-3 text-secondary text-muted">{{ post.miniTitle }}</h3>
      <h3 class="h6 ps-5 pt-3 text-secondary text-muted">{{ post.OneWordPov }} and {{ post.mark }}/10 </h3>
      <p class="h6 ps-5 pt-3 text-secondary text-muted">Location : {{ post.location }}</p>
      <div class="ps-5 pt-3 pe-5 text-break">
      {{ post.reviewArticle }}
      </div>
     <div class="ps-3 pb-3 mt-5"> 
    {% if app.user.id == post.user.id  %}
    
        <a href="{{  path('app_posts_edit',{slug: post.slug}) }}" class="btn btn-outline-dark">Edit</a> 
        <a href="#" onclick="event.preventDefault(); confirm('Are you sure?') && document.getElementById('js-post-delete-form').submit(); " class="btn btn-outline-dark">Delete</a>
   
		{% endif %}
    

 </div>
  </article>


</div>
</div>



<form id="js-post-delete-form" action="{{  path('app_posts_delete',{slug: post.slug}) }}" method="post" style="display:none;"> 
  <input type="hidden" name="csrf_token" value="{{ csrf_token('post_deletion'~ post.slug) }}">
  <input type="hidden" name="_method" value="DELETE">
</form>
{% endblock %}